appname = eventx
httpport = 8080
runmode = dev
copyrequestbody = true
viewspath = views
staticdir = static
CACHE_TTL = 300
APPROVED_TICKET_HOSTS = ticketmaster.com, www.ticketmaster.com, livenation.com, www.livenation.com, ticketmaster.co.uk